productions = {
    (52, 1): ["PROGRAM", "IDENTIFICADOR", ";", "BLOCO", "."],
    (53, 2): ["DCLROT", "DCLCONST", "DCLVAR", "DCLPROC", "CORPO"],
    (53, 3): ["DCLROT", "DCLCONST", "DCLVAR", "DCLPROC", "CORPO"],
    (53, 4): ["DCLROT", "DCLCONST", "DCLVAR", "DCLPROC", "CORPO"],
    (53, 5): ["DCLROT", "DCLCONST", "DCLVAR", "DCLPROC", "CORPO"],
    (53, 6): ["DCLROT", "DCLCONST", "DCLVAR", "DCLPROC", "CORPO"],
    (54, 2): ["LABEL", "LID", ";"],
    (54, 3): ["NULL"],
    (54, 4): ["NULL"],
    (54, 5): ["NULL"],
    (54, 6): ["NULL"],
    (55, 25): ["IDENTIFICADOR", "REPIDENT"],
    (56, 39): ["NULL"],
    (56, 46): [",", "IDENTIFICADOR", "REPIDENT"],
    (56, 47): ["NULL"],
    (57, 3): ["CONST", "IDENTIFICADOR", "=", "INTEIRO", ";", "LDCONST"],
    (57, 4): ["NULL"],
    (57, 5): ["NULL"],
    (57, 6): ["NULL"],
    (58, 4): ["NULL"],
    (58, 5): ["NULL"],
    (58, 6): ["NULL"],
    (58, 25): ["IDENTIFICADOR", "=", "INTEIRO", ";", "LDCONST"],
    (59, 4): ["VAR", "LID", ":", "TIPO", ";", "LDVAR"],
    (59, 5): ["NULL"],
    (59, 6): ["NULL"],
    (60, 5): ["NULL"],
    (60, 6): ["NULL"],
    (60, 25): ["LID", ":", "TIPO", ";", "LDVAR"],
    (61, 8): ["INTEGER"],
    (61, 9): ["ARRAY", "[", "INTEIRO", "..", "INTEIRO", "]", "OF", "INTEGER"],
    (62, 5): ["PROCEDURE", "IDENTIFICADOR", "DEFPAR", ";", "BLOCO", ";", "DCLPROC"],
    (62, 6): ["NULL"],
    (63, 36): ["(", "LID", ":", "INTEGER", ")"],
    (63, 39): ["NULL"],
    (64, 6): ["BEGIN", "COMANDO", "REPCOMANDO", "END"],
    (65, 7): ["NULL"],
    (65, 47): [";", "COMANDO", "REPCOMANDO"],
    (66, 6): ["CORPO"],
    (66, 7): ["NULL"],
    (66, 11): ["CALL", "IDENTIFICADOR", "PARAMETROS"],
    (66, 12): ["GOTO", "IDENTIFICADOR"],
    (66, 13): ["IF", "EXPRESSAO", "THEN", "COMANDO", "ELSEPARTE"],
    (66, 15): ["NULL"],
    (66, 16): ["WHILE", "EXPRESSAO", "DO", "COMANDO"],
    (66, 18): ["REPEAT", "COMANDO", "UNTIL", "EXPRESSAO"],
    (66, 19): ["NULL"],
    (66, 20): ["READLN", "(", "VARIAVEL", "REPVARIAVEL", ")"],
    (66, 21): ["WRITELN", "(", "ITEMSAIDA", "REPITEM", ")"],
    (66, 25): ["IDENTIFICADOR", "RCOMID"],





}